import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Layout from "../components/Layout";

import happyMusic from "../public/images/happyMusic.svg";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NFTickets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <div className="h-screen flex">
          <div className="basis-1/2 flex justify-center items-center">
            <div className="w-2/3">
              <Image
                src={happyMusic}
                alt=""
              />
            </div>
          </div>
          <div className="basis-1/2 flex justify-center items-center">
            <div className="flex flex-col w-2/3">
              <h1 className="text-white text-4xl font-bold">Secure concert tickets</h1>
              <p>Introducing, the best way of selling concert tickets. Based on the Gear blockchain and NFT technology. </p>

              <div className="py-4 flex justify-center items-center">
                <button className="flex-0 p-2 font-bold bg-indigo-600 border-2 border-indigo-600 rounded hover:bg-transparent transition-all">Get started</button>
              </div>
            </div>
          </div>
        </div>
        <div className="relative h-screen bg-indigo-600">
          <div className="absolute top-0 left-0 w-full overflow-hidden">
            <svg className="relative block w-[calc(106%+1.3px)] h-[144px]" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
              <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" className="fill-slate-800"></path>
            </svg>
          </div>
          <div className="absolute top-0 h-full left-0 w-full text-white">
            <h1>Otro título</h1>
          </div>

          hgola
        </div>
      </Layout>
    </>
  )
}
