[package]
name = "event"
version = "0.1.1"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
multitoken-io = { git = "https://github.com/gear-dapps/multitoken.git", tag = "0.3.3" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.2" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], branch = "stable" }
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
